language: php
php:
    - '7.1'
install:
    - composer install
script:
    - vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/
after_success:
    - bin/build
deploy:
    provider: releases
    api_key:
        secure: "x3B1NQ2CJllb3QM6/wGMYVsBWETMteKnRbwsPumEWlegqCsWQ24dbTUARxjZc8VRGOq00ZLqwogW2byMVFOh49MWYS4B8wfXRf3pFMJ8PjaDiD5s3q194/S5jYXWAudj47/xkRuDiQ7LtelRpKtOVEiGP+bhx99bxoa5gYGqTzCy3IFoMcvK+lD9qd/a7RCO9ggM7eDMDG3m6MFb0LSGN3qQvwAY6pBIC+jvvonEjD7feW8LSfb4OdlYu59/DJ0sOhw1BcJ5dQjqHZnLFZJDZIS1XKShDGAAiGc2G6Ll6zEcXdhfFata1ctBetqNTRF+7bv7BMKpssZLcNwYaAXsYvfH+xO6dJUW8zYzRsS6dfAwSfbWRXm+SAatDaf5D1wmxeDqGq0x7qFSTbLlQ4ILZemy0ktsAjn79ZwDWLNUKK+OUrZwpb92fUe8mRqXIIiKbXzS2ZtVhcwcQjpEGyFlzeYvrZIV1H0HbFt2M7F3/W6qnGTJliH/UpUEvxQA8XfTP5CcdY4X+s/YClGQYwBihkDlGwE5156mEoWHbQYw0J2Y507eSEdcsA6CCbfrXMeHMo9250CAM8riuaOF2bNXae+8QcVOqRYL+Utz/T8wXhoBR2+BoRUfOwR13OB0rDOK1gVmrswzLHzWi+vCQZRD0mgjSlwnEYuPf6LrSdTIY0M="
    file: dist/fakturoid-sdk.zip
    skip_cleanup: true
    on:
        tags: true
        php: '7.1'
