language: php
php:
    - '7.1'
install:
    - composer install
script:
    - vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/
after_success:
    - bin/build
deploy:
    provider: releases
    api_key:
        secure: cMB5PZmaTjfSaFgN4VHcR/g4mS5TQrkgcqqhhEjoEI+d1IxSBzaHDAm1tCX/YMTWQk/DUNpwBBkzuxKlZbYKmYcaO5K0wvNNoSfyoBYhD1di9h4pHcQ8MYMCTOFQ+4MC6FqRou6pvlDJbmR0nqbla2+tuoL5TeUyhz+cO9Hl3+YHZf4FagD7ijdKaq1LDRJyWhwh1/4Ln4UGnhuL7ebv922K5T5DxjsBA6Y95TRA+cgfJ4V4lEMJLo/2/VO8RtwzO12Xy5JunuQCsN94DfG6hWLplTDZpJSsrqmaTij0gTCkKTdzti5ScaLuM2vqx1c+vS79br54MYr7Uw1Nm68RmKr/BTcHOYV2V2YmKWcjtY+iUkm4yHGa8e6PUG3Thhl+/ULtGcy18+7aXtfVP1lQjFHpwW3VLaTay7w0nCXC76wAL/n3BdIPnytvnTbNK1P9fphNkyamwoVYz+6cKAV4mrmlLP/LXr6nBqwM/49cLIiDSD573lE5TXoPPObZI2ujuT30JOwcobh/V1+vVpewXMvcC5pkRPsjUSMUa/1qAmznTHOKfZPdOkTlTItSfFRermy8Rq3hap+AwbAOqHCABUjlsDy65iMEql85XnqI6un4ZljwxZRGyMQ31C+PtxfWIqGCjE8rB/FxWgYuNYUFWbrE4OG+Kfd0+ojbJDEVXVs=
    file: dist/fakturoid-sdk.zip
    skip_cleanup: true
    on:
        tags: true
        php: '7.1'
